package corba;

/**
* calc/CalculadoraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from modulo.idl
* Quarta-feira, 26 de Novembro de 2014 17h08min05s BRST
*/

public final class CalculadoraHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Calculadora value = null;

  public CalculadoraHolder ()
  {
  }

  public CalculadoraHolder (corba.Calculadora initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CalculadoraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CalculadoraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CalculadoraHelper.type ();
  }

}
