package calc;


/**
* calc/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from modulo.idl
* Quarta-feira, 26 de Novembro de 2014 17h08min05s BRST
*/

public interface CalculadoraOperations 
{
  int somar (int valor1, int valor2);
  int subtrair (int valor1, int valor2);
  int multiplicar (int valor1, int valor2);
  double dividir (int valor1, int valor2);
} // interface CalculadoraOperations
